### ISSUE TITLE
Observing "build_odl_topology ERROR: <type 'exceptions.KeyError'>" in pathman.log 

### ISSUE THREAD

**Issue by abhinavp001** [CiscoDevNet/pathman-sr#10]
Hi,

Observing "build_odl_topology ERROR: <type 'exceptions.KeyError'>" in pathman.log . 
Also i do not see any topology or any option to create path in web browser connected to pathman-sr.

Please find below pathman log.

9821 2018-01-25 15:35:14.481 UTC root:<module>     INFO: This is initializing the log
9821 2018-01-25 15:35:15.017 UTC root:get_url      INFO: Url get Status: 200
9821 2018-01-25 15:35:15.040 UTC root:get_url      INFO: Url get Status: 200
9821 2018-01-25 15:35:15.041 UTC root:add_node     INFO: New node: Node(name=u'0003.0003.0003.02', id=u'0003.0003.0003.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], 

sid='')
9821 2018-01-25 15:35:15.041 UTC root:add_node     INFO: New node: Node(name=u'0002.0002.0002.02', id=u'0002.0002.0002.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], 

sid='')
9821 2018-01-25 15:35:15.041 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr4', id=u'0004.0004.0004', loopback=u'4.4.4.4', portlist=[u'19.1.1.2', u'21.1.1.2'], pcc='', 

pcep_type='', prefix=[u'19.1.1.0/24', u'21.1.1.0/24', u'4.4.4.4/32'], sid='')
9821 2018-01-25 15:35:15.042 UTC root:add_node     INFO: New node: Node(name=u'0001.0001.0001.01', id=u'0001.0001.0001.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], 

sid='')
9821 2018-01-25 15:35:15.042 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr5', id=u'0005.0005.0005', loopback=u'5.5.5.5', portlist=[u'15.1.1.2', u'18.1.1.2', 

u'19.1.1.1'], pcc='', pcep_type='', prefix=[u'15.1.1.0/24', u'18.1.1.0/24', u'19.1.1.0/24', u'5.5.5.5/32'], sid='')
9821 2018-01-25 15:35:15.043 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr6', id=u'0006.0006.0006', loopback=u'6.6.6.6', portlist=[u'17.1.1.2', u'18.1.1.1', 

u'21.1.1.1'], pcc='', pcep_type='', prefix=[u'17.1.1.0/24', u'18.1.1.0/24', u'21.1.1.0/24', u'6.6.6.6/32'], sid='')
9821 2018-01-25 15:35:15.043 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr2', id=u'0002.0002.0002', loopback=u'2.2.2.2', portlist=[u'13.1.1.2', u'15.1.1.1', 

u'16.1.1.1'], pcc='', pcep_type='', prefix=[u'13.1.1.0/24', u'15.1.1.0/24', u'16.1.1.0/24', u'2.2.2.2/32'], sid='')
9821 2018-01-25 15:35:15.044 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr1', id=u'0001.0001.0001', loopback=u'1.1.1.1', portlist=[u'13.1.1.1', u'14.1.1.1'], 

pcc=u'pcc://1.1.1.1', pcep_type='07', prefix=[u'1.1.1.1/32', u'13.1.1.0/24', u'14.1.1.0/24'], sid='')
9821 2018-01-25 15:35:15.044 UTC root:add_node     INFO: New node: Node(name=u'0005.0005.0005.01', id=u'0005.0005.0005.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], 

sid='')
9821 2018-01-25 15:35:15.044 UTC root:add_node     INFO: New node: Node(name=u'0004.0004.0004.01', id=u'0004.0004.0004.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], 

sid='')
9821 2018-01-25 15:35:15.045 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr3', id=u'0003.0003.0003', loopback=u'3.3.3.3', portlist=[u'14.1.1.2', u'16.1.1.2', 

u'17.1.1.1'], pcc='', pcep_type='', prefix=[u'14.1.1.0/24', u'16.1.1.0/24', u'17.1.1.0/24', u'3.3.3.3/32'], sid='')
9821 2018-01-25 15:35:15.045 UTC root:add_node     INFO: New node: Node(name=u'0004.0004.0004.02', id=u'0004.0004.0004.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], 

sid='')
9821 2018-01-25 15:35:15.045 UTC root:add_node     INFO: New node: Node(name=u'0006.0006.0006.01', id=u'0006.0006.0006.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], 

sid='')
9821 2018-01-25 15:35:15.046 UTC root:add_node     INFO: New node: Node(name=u'0005.0005.0005.03', id=u'0005.0005.0005.03', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], 

sid='')
9821 2018-01-25 15:35:15.046 UTC root:node_structure INFO: [Node(name=u'0003.0003.0003.02', id=u'0003.0003.0003.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), 

Node(name=u'0002.0002.0002.02', id=u'0002.0002.0002.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'10d01_vfemu-evr4', id=u'0004.0004.0004', 

loopback=u'4.4.4.4', portlist=[u'19.1.1.2', u'21.1.1.2'], pcc='', pcep_type='', prefix=[u'19.1.1.0/24', u'21.1.1.0/24', u'4.4.4.4/32'], sid=''), Node(name=u'0001.0001.0001.01', 

id=u'0001.0001.0001.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'10d01_vfemu-evr5', id=u'0005.0005.0005', loopback=u'5.5.5.5', portlist=[u'15.1.1.2', 

u'18.1.1.2', u'19.1.1.1'], pcc='', pcep_type='', prefix=[u'15.1.1.0/24', u'18.1.1.0/24', u'19.1.1.0/24', u'5.5.5.5/32'], sid=''), Node(name=u'10d01_vfemu-evr6', id=u'0006.0006.0006', 

loopback=u'6.6.6.6', portlist=[u'17.1.1.2', u'18.1.1.1', u'21.1.1.1'], pcc='', pcep_type='', prefix=[u'17.1.1.0/24', u'18.1.1.0/24', u'21.1.1.0/24', u'6.6.6.6/32'], sid=''), Node

(name=u'10d01_vfemu-evr2', id=u'0002.0002.0002', loopback=u'2.2.2.2', portlist=[u'13.1.1.2', u'15.1.1.1', u'16.1.1.1'], pcc='', pcep_type='', prefix=[u'13.1.1.0/24', u'15.1.1.0/24', 

u'16.1.1.0/24', u'2.2.2.2/32'], sid=''), Node(name=u'10d01_vfemu-evr1', id=u'0001.0001.0001', loopback=u'1.1.1.1', portlist=[u'13.1.1.1', u'14.1.1.1'], pcc=u'pcc://1.1.1.1', pcep_type='07', 

prefix=[u'1.1.1.1/32', u'13.1.1.0/24', u'14.1.1.0/24'], sid=''), Node(name=u'0005.0005.0005.01', id=u'0005.0005.0005.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), 

Node(name=u'0004.0004.0004.01', id=u'0004.0004.0004.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'10d01_vfemu-evr3', id=u'0003.0003.0003', 

loopback=u'3.3.3.3', portlist=[u'14.1.1.2', u'16.1.1.2', u'17.1.1.1'], pcc='', pcep_type='', prefix=[u'14.1.1.0/24', u'16.1.1.0/24', u'17.1.1.0/24', u'3.3.3.3/32'], sid=''), Node

(name=u'0004.0004.0004.02', id=u'0004.0004.0004.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'0006.0006.0006.01', id=u'0006.0006.0006.01', 

loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'0005.0005.0005.03', id=u'0005.0005.0005.03', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], 

sid='')]
9821 2018-01-25 15:35:15.046 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0003.0003.0003.02 is: 10d01_vfemu-evr3
9821 2018-01-25 15:35:15.047 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0002.0002.0002.02 is: 10d01_vfemu-evr2
9821 2018-01-25 15:35:15.047 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0001.0001.0001.01 is: 10d01_vfemu-evr1
9821 2018-01-25 15:35:15.047 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0005.0005.0005.01 is: 10d01_vfemu-evr5
9821 2018-01-25 15:35:15.047 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0004.0004.0004.01 is: 10d01_vfemu-evr4
9821 2018-01-25 15:35:15.048 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0006.0006.0006.01 is: 10d01_vfemu-evr6
9821 2018-01-25 15:35:15.048 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0005.0005.0005.03 is: 10d01_vfemu-evr5
9821 2018-01-25 15:35:15.048 UTC root:pseudo_net_build INFO: []
9821 2018-01-25 15:35:15.120 UTC root:_get_url     INFO: status code: 200
9821 2018-01-25 15:35:15.126 UTC root:build_odl_topology ERROR: <type 'exceptions.KeyError'>
9821 2018-01-25 15:35:15.127 UTC root:__init__     INFO: patterned to '/pathman'
9821 2018-01-25 15:35:15.130 UTC root:__init__     INFO: Pathman REST API Launched on port 8020

**Comment by nikmon2** [comment]
Hi, 
A. Can you share the output for the pcep and bgp-ls topology?
     - json format please :)
     By mail or posting.

B. What router-os, versions are you using?

It's hard to say what's wrong without that.
But I would check:
1. Is your bgp-ls reported router-id the same as your pcep address/id?
   Not having them match should not cause a match.
2. You have a lot of pseudo nodes being reported, and I would have expected some networks being logged.


Cheers,
Niklas

**Comment by abhinavp001** [comment]
Hi Niklas,

Please find attached pcep and bgp-ls topology.
Is SR-PATHMAN uses /restconf/operational/network-topology:network-topology/topology/example-linkstate-topology  or /restconf/operational/bgp-rib:bgp-rib.

As i do not see SID value in linkstate-topology. but they are available in bgp-rib output

Regards,
Abhinav
[pcep-topology-output.txt](https://github.com/CiscoDevNet/pathman-sr/files/1678011/pcep-topology-output.txt)

[bgp-linkstate-topology-1.txt](https://github.com/CiscoDevNet/pathman-sr/files/1678026/bgp-linkstate-topology-1.txt)

**Comment by nikmon2** [comment]
Hi Abhinav,

Router-ID's are fine and so is the node-format.

It looks like the issue is related to the format of the reply to:
```
/restconf/operational/bgp-rib:bgp-rib/rib/example-bgp-rib/loc-rib/tables/bgp-linkstate:linkstate-address-family/bgp-linkstate:linkstate-subsequent-address-family/linkstate-routes
```

This is the URL used to find SIDs from bgp-rib, and I suspect that your fields may be different than what I expect them to be.

Can you share that reply?

Cheers,
Niklas

**Comment by abhinavp001** [comment]
Hi Niklas,

Please find output attached .

Regards,
Abhinav
[linkstate-routes.txt](https://github.com/CiscoDevNet/pathman-sr/files/1681166/linkstate-routes.txt)

**Comment by nikmon2** [comment]
Thanks Abhinav,
I have identified the issue; some nodes are missing a tag in their output.
- Fix is easy, but I need to look at what that means.

Stay tuned.

Cheers,
Niklas

**Comment by nikmon2** [comment]
Fixed, please pull new version and let me know if it works for you.

Cheers,
Niklas

**Comment by abhinavp001** [comment]
Hi Niklas,

Thanks, crash issue is resolved.
But still i do not see topology and other UI option after connecting through URL.

On a linux machine i have installed ODL and SR_PATHMAN  and tried to access it through VNC server connected to SR-PATHMAN.

Could you please point if i am missing some setting ?
Followed all steps in Wiki and there is no error message reported in pathman.log.

used below command to link app.js 

 pathman-sr-master]# sed -i 's/localhost/10.35.227.120/g' client/pathman_sr/js/app.js

Regards,
Abhinav

**Comment by abhinavp001** [comment]
Hi Niklas,

One more issue i found , i do not see below log 

UTC root:getTopo      INFO: Topo build with 8 nodes

Please find below pathman.log with fix.
5704 2018-02-02 02:14:03.177 UTC root:<module>     INFO: This is initializing the log
5704 2018-02-02 02:14:03.533 UTC root:get_url      INFO: Url get Status: 200
5704 2018-02-02 02:14:03.553 UTC root:get_url      INFO: Url get Status: 200
5704 2018-02-02 02:14:03.553 UTC root:add_node     INFO: New node: Node(name=u'0003.0003.0003.02', id=u'0003.0003.0003.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid='')
5704 2018-02-02 02:14:03.554 UTC root:add_node     INFO: New node: Node(name=u'0002.0002.0002.02', id=u'0002.0002.0002.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid='')
5704 2018-02-02 02:14:03.554 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr4', id=u'0004.0004.0004', loopback=u'4.4.4.4', portlist=[u'19.1.1.2', u'21.1.1.2'], pcc='', pcep_type='', prefix=[u'19.1.1.0/24', u'21.1.1.0/24', u'4.4.4.4/32'], sid='')
5704 2018-02-02 02:14:03.554 UTC root:add_node     INFO: New node: Node(name=u'0001.0001.0001.01', id=u'0001.0001.0001.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid='')
5704 2018-02-02 02:14:03.554 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr5', id=u'0005.0005.0005', loopback=u'5.5.5.5', portlist=[u'15.1.1.2', u'18.1.1.2', u'19.1.1.1'], pcc='', pcep_type='', prefix=[u'15.1.1.0/24', u'18.1.1.0/24', u'19.1.1.0/24', u'5.5.5.5/32'], sid='')
5704 2018-02-02 02:14:03.555 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr6', id=u'0006.0006.0006', loopback=u'6.6.6.6', portlist=[u'17.1.1.2', u'18.1.1.1', u'21.1.1.1'], pcc='', pcep_type='', prefix=[u'17.1.1.0/24', u'18.1.1.0/24', u'21.1.1.0/24', u'6.6.6.6/32'], sid='')
5704 2018-02-02 02:14:03.555 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr2', id=u'0002.0002.0002', loopback=u'2.2.2.2', portlist=[u'13.1.1.2', u'15.1.1.1', u'16.1.1.1'], pcc='', pcep_type='', prefix=[u'13.1.1.0/24', u'15.1.1.0/24', u'16.1.1.0/24', u'2.2.2.2/32'], sid='')
5704 2018-02-02 02:14:03.555 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr1', id=u'0001.0001.0001', loopback=u'1.1.1.1', portlist=[u'13.1.1.1', u'14.1.1.1'], pcc=u'pcc://1.1.1.1', pcep_type='07', prefix=[u'1.1.1.1/32', u'13.1.1.0/24', u'14.1.1.0/24'], sid='')
5704 2018-02-02 02:14:03.555 UTC root:add_node     INFO: New node: Node(name=u'0005.0005.0005.01', id=u'0005.0005.0005.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid='')
5704 2018-02-02 02:14:03.556 UTC root:add_node     INFO: New node: Node(name=u'0004.0004.0004.01', id=u'0004.0004.0004.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid='')
5704 2018-02-02 02:14:03.556 UTC root:add_node     INFO: New node: Node(name=u'10d01_vfemu-evr3', id=u'0003.0003.0003', loopback=u'3.3.3.3', portlist=[u'14.1.1.2', u'16.1.1.2', u'17.1.1.1'], pcc='', pcep_type='', prefix=[u'14.1.1.0/24', u'16.1.1.0/24', u'17.1.1.0/24', u'3.3.3.3/32'], sid='')
5704 2018-02-02 02:14:03.556 UTC root:add_node     INFO: New node: Node(name=u'0004.0004.0004.02', id=u'0004.0004.0004.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid='')
5704 2018-02-02 02:14:03.556 UTC root:add_node     INFO: New node: Node(name=u'0006.0006.0006.01', id=u'0006.0006.0006.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid='')
5704 2018-02-02 02:14:03.557 UTC root:add_node     INFO: New node: Node(name=u'0005.0005.0005.03', id=u'0005.0005.0005.03', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid='')
5704 2018-02-02 02:14:03.557 UTC root:node_structure INFO: [Node(name=u'0003.0003.0003.02', id=u'0003.0003.0003.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'0002.0002.0002.02', id=u'0002.0002.0002.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'10d01_vfemu-evr4', id=u'0004.0004.0004', loopback=u'4.4.4.4', portlist=[u'19.1.1.2', u'21.1.1.2'], pcc='', pcep_type='', prefix=[u'19.1.1.0/24', u'21.1.1.0/24', u'4.4.4.4/32'], sid=''), Node(name=u'0001.0001.0001.01', id=u'0001.0001.0001.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'10d01_vfemu-evr5', id=u'0005.0005.0005', loopback=u'5.5.5.5', portlist=[u'15.1.1.2', u'18.1.1.2', u'19.1.1.1'], pcc='', pcep_type='', prefix=[u'15.1.1.0/24', u'18.1.1.0/24', u'19.1.1.0/24', u'5.5.5.5/32'], sid=''), Node(name=u'10d01_vfemu-evr6', id=u'0006.0006.0006', loopback=u'6.6.6.6', portlist=[u'17.1.1.2', u'18.1.1.1', u'21.1.1.1'], pcc='', pcep_type='', prefix=[u'17.1.1.0/24', u'18.1.1.0/24', u'21.1.1.0/24', u'6.6.6.6/32'], sid=''), Node(name=u'10d01_vfemu-evr2', id=u'0002.0002.0002', loopback=u'2.2.2.2', portlist=[u'13.1.1.2', u'15.1.1.1', u'16.1.1.1'], pcc='', pcep_type='', prefix=[u'13.1.1.0/24', u'15.1.1.0/24', u'16.1.1.0/24', u'2.2.2.2/32'], sid=''), Node(name=u'10d01_vfemu-evr1', id=u'0001.0001.0001', loopback=u'1.1.1.1', portlist=[u'13.1.1.1', u'14.1.1.1'], pcc=u'pcc://1.1.1.1', pcep_type='07', prefix=[u'1.1.1.1/32', u'13.1.1.0/24', u'14.1.1.0/24'], sid=''), Node(name=u'0005.0005.0005.01', id=u'0005.0005.0005.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'0004.0004.0004.01', id=u'0004.0004.0004.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'10d01_vfemu-evr3', id=u'0003.0003.0003', loopback=u'3.3.3.3', portlist=[u'14.1.1.2', u'16.1.1.2', u'17.1.1.1'], pcc='', pcep_type='', prefix=[u'14.1.1.0/24', u'16.1.1.0/24', u'17.1.1.0/24', u'3.3.3.3/32'], sid=''), Node(name=u'0004.0004.0004.02', id=u'0004.0004.0004.02', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'0006.0006.0006.01', id=u'0006.0006.0006.01', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid=''), Node(name=u'0005.0005.0005.03', id=u'0005.0005.0005.03', loopback='', portlist=[], pcc='', pcep_type='', prefix=[], sid='')]
5704 2018-02-02 02:14:03.557 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0003.0003.0003.02 is: 10d01_vfemu-evr3
5704 2018-02-02 02:14:03.557 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0002.0002.0002.02 is: 10d01_vfemu-evr2
5704 2018-02-02 02:14:03.557 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0001.0001.0001.01 is: 10d01_vfemu-evr1
5704 2018-02-02 02:14:03.557 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0005.0005.0005.01 is: 10d01_vfemu-evr5
5704 2018-02-02 02:14:03.558 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0004.0004.0004.01 is: 10d01_vfemu-evr4
5704 2018-02-02 02:14:03.558 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0004.0004.0004.02 is: 10d01_vfemu-evr4
5704 2018-02-02 02:14:03.558 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0006.0006.0006.01 is: 10d01_vfemu-evr6
5704 2018-02-02 02:14:03.558 UTC root:pseudo_net_build INFO: Owner of Pseduo: 0005.0005.0005.03 is: 10d01_vfemu-evr5
5704 2018-02-02 02:14:03.558 UTC root:pseudo_net_build INFO: []
5704 2018-02-02 02:14:03.604 UTC root:_get_url     INFO: status code: 200
5704 2018-02-02 02:14:03.608 UTC root:node_sr_update ERROR: No BGP SID for: 10d01_vfemu-evr3.02
5704 2018-02-02 02:14:03.608 UTC root:node_sr_update ERROR: No BGP SID for: 10d01_vfemu-evr2.02
5704 2018-02-02 02:14:03.609 UTC root:node_sr_update INFO: SR sid updated for: 10d01_vfemu-evr4 from bgp
5704 2018-02-02 02:14:03.609 UTC root:node_sr_update ERROR: No BGP SID for: 10d01_vfemu-evr1.01
5704 2018-02-02 02:14:03.609 UTC root:node_sr_update INFO: SR sid updated for: 10d01_vfemu-evr5 from bgp
5704 2018-02-02 02:14:03.609 UTC root:node_sr_update INFO: SR sid updated for: 10d01_vfemu-evr6 from bgp
5704 2018-02-02 02:14:03.609 UTC root:node_sr_update INFO: SR sid updated for: 10d01_vfemu-evr2 from bgp
5704 2018-02-02 02:14:03.609 UTC root:node_sr_update INFO: SR sid updated for: 10d01_vfemu-evr1 from bgp
5704 2018-02-02 02:14:03.609 UTC root:node_sr_update ERROR: No BGP SID for: 10d01_vfemu-evr5.01
5704 2018-02-02 02:14:03.609 UTC root:node_sr_update ERROR: No BGP SID for: 10d01_vfemu-evr4.01
5704 2018-02-02 02:14:03.609 UTC root:node_sr_update INFO: SR sid updated for: 10d01_vfemu-evr3 from bgp
5704 2018-02-02 02:14:03.610 UTC root:node_sr_update ERROR: No BGP SID for: 10d01_vfemu-evr4.02
5704 2018-02-02 02:14:03.610 UTC root:node_sr_update ERROR: No BGP SID for: 10d01_vfemu-evr6.01
5704 2018-02-02 02:14:03.610 UTC root:node_sr_update ERROR: No BGP SID for: 10d01_vfemu-evr5.03
5704 2018-02-02 02:14:03.618 UTC root:__init__     INFO: patterned to '/pathman'
5704 2018-02-02 02:14:03.621 UTC root:__init__     INFO: Pathman REST API Launched on port 8020

Regards,
Abhinav

**Comment by nikmon2** [comment]
Hi Abhinav,
Messages look OK. Topology map should be displayed even if SIDs are missing.
These are the steps to run:

1. On your host, assuming it's IP is: 10.35.227.120, start the server:
```
./rest_server_v6.py
```
2. Point your browser to <http://10.35.227.120:8020/cisco-ctao/apps/pathman_sr/index.html>

I will run a test on your data and see if I find somehting else.

Cheers,
Niklas

**Comment by nikmon2** [comment]
Hi Abhinav,

I took your example-linkstate output, put in a file called topofile.py, and added "topo = ":
```
topo = {
    "topology": [
```

Then in pathman_sr, line 1114, I added and import from topofile:
```
    global my_topology
    from topofile import topo
```

Then a few lines below:
```
    try:
       #  my_topology = get_url(get_topo)
        my_topology = topo
```

This is enough to get your [Topology View](https://github.com/CiscoDevNet/pathman-sr/blob/master/dCloud/media/cloud_Workstation_252_202504CA.png) to display.
- I did not test to add PCEP or BGP-SID info.

Cheers,
Niklas

**Comment by nikmon2** [comment]
Looking at your topo, it seems all your links are shared broadcast networks - not point-to-point links.
The name.01, name.02 etc are pseudo nodes for the shared networks.

If you configured your links to be point-to-point, which they seem to be, the pseudo-nodes would disappear.

Under router isis:
```
 !
 interface GigabitEthernet0/0/0/1
  point-to-point
  address-family ipv4 unicast
  !
  address-family ipv6 unicast
  !
 !
```
Cheers,
Niklas

**Comment by abhinavp001** [comment]
Hi Niklas,

Shouldn't sr-pathman update topo_data.py file everytime it runs sucessfully.
In my case it is not getting updated.

Still i do not see topology in browser. nor any other option.
Seems that something wrong in my setup. Please find attached screen shot of browser.

I am not using Cisco router but some other vendor router will it have any impact.

Regards,
Abhinav
![browser output](https://user-images.githubusercontent.com/35225941/36280068-2852d03a-12bf-11e8-8887-7c463d3c1188.png)

**Comment by nikmon2** [comment]
Hi Abhinav,

1. The topo_data.py file is not updated. It was used in a previous version that had geo-coordinates for routers.
2. You should always see something in your browser. The app is split in a front- and back-end.
The UI is found at your http://localhost_ip:8020/cisco-ctao/apps/pathman_sr/index.html, after that the rest-server has been started. (./restserver_v6.py) The UI should display an error if the backend has issues.
3. Router vendor should not matter much, but the reply format may be different than what I expect it to be. That said, I used your output and generated a topo. <https://github.com/CiscoDevNet/pathman-sr/blob/master/dCloud/media/cloud_Workstation_252_202504CA.png>
4. There is an issue with path setup and pseudo-nodes, but that is only an issue after you have your topology up. I have not found a good solution for that yet.

Cheers,
Niklas

**Comment by abhinavp001** [comment]
Hi Niklas,

Today observing below issue, could you please help to resolve it ?

Error: http://localhost:8020/cisco-ctao/apps/pathman_sr/js/app.js: ReferenceError: Can't find variable: angular

Regards,
Abhinav

**Comment by nikmon2** [comment]
Hi Abhinav,

That is not the correct link, but it should display the actual file app.js.

This is the link: <http://localhost:8020/cisco-ctao/apps/pathman_sr/index.html>
This [Dockerfile](https://github.com/CiscoDevNet/pathman-sr/blob/master/docker/Dockerfile) shows what's needed to make pathman sr run on CentOS, Ubuntu would be similar.

Cheers,
Niklas

**Comment by abhinavp001** [comment]
Hi Niklas.

Closing this issue , as issue is resolved thanks for your support.

Regards,
Abhinav

**Comment by foxroot55** [comment]
Hi Niklas unfortunately i have the same issue too my output

1615 2023-05-18 20:35:04.038 UTC root:add_node     INFO: New node: Node(name=u'101058054', id=u'101058054', loopback='', portlist=[u'172.16.0.18', u'172.16.0.22', u'172.16.0.26', u'172.16.0.41', u'172.16.3.5'], pcc='', pcep_type='', prefix=[u'10.181.184.0/24', u'172.16.0.16/30', u'172.16.0.20/30', u'172.16.0.24/30', u'172.16.0.40/30', u'172.16.3.4/30', u'6.6.6.6/32'], sid='')
1615 2023-05-18 20:35:04.039 UTC root:node_structure INFO: [Node(name=u'370546198', id=u'370546198', loopback='', portlist=[u'172.16.1.2', u'172.16.1.5'], pcc='', pcep_type='', prefix=[u'172.16.1.0/30', u'172.16.1.4/30', u'22.22.22.22/32'], sid=''), Node(name=u'67372036', id=u'67372036', loopback='', portlist=[u'172.16.0.10', u'172.16.0.17', u'172.16.2.6'], pcc='', pcep_type='', prefix=[u'10.181.184.0/24', u'172.16.0.16/30', u'172.16.0.8/30', u'172.16.2.4/30', u'4.4.4.4/32'], sid=''), Node(name=u'33686018', id=u'33686018', loopback='', portlist=[u'172.16.0.34', u'172.16.0.38', u'172.16.0.42', u'172.16.1.6'], pcc='', pcep_type='', prefix=[u'10.181.184.0/24', u'11.11.11.11/32', u'172.16.0.32/30', u'172.16.0.36/30', u'172.16.0.40/30', u'172.16.1.4/30', u'2.2.2.2/32', u'22.22.0.0/32', u'22.22.22.22/32', u'33.33.33.33/32'], sid=''), Node(name=u'185273099', id=u'185273099', loopback='', portlist=[u'172.16.2.2', u'172.16.2.5'], pcc='', pcep_type='', prefix=[u'11.11.11.11/32', u'172.16.2.0/30', u'172.16.2.4/30'], sid=''), Node(name=u'16843009', id=u'16843009', loopback='', portlist=[u'172.16.0.2', u'172.16.0.33', u'172.16.0.37', u'172.16.1.1'], pcc='', pcep_type='', prefix=[u'1.1.1.1/32', u'10.181.184.0/24', u'11.11.11.11/32', u'172.16.0.0/30', u'172.16.0.32/30', u'172.16.0.36/30', u'172.16.1.0/30', u'22.22.0.0/32', u'22.22.22.22/32', u'33.33.33.33/32'], sid=''), Node(name=u'84215045', id=u'84215045', loopback='', portlist=[u'172.16.0.14', u'172.16.0.21', u'172.16.0.25', u'172.16.3.1'], pcc='', pcep_type='', prefix=[u'10.181.184.0/24', u'172.16.0.12/30', u'172.16.0.20/30', u'172.16.0.24/30', u'172.16.3.0/30', u'5.5.5.5/32'], sid=''), Node(name=u'741092396', id=u'741092396', loopback='', portlist=[u'172.16.3.2', u'172.16.3.6'], pcc='', pcep_type='', prefix=[u'172.16.3.0/30', u'172.16.3.4/30', u'44.44.44.44/32'], sid=''), Node(name=u'50529027', id=u'50529027', loopback='', portlist=[u'172.16.0.1', u'172.16.0.13', u'172.16.0.9', u'172.16.2.1'], pcc='', pcep_type='', prefix=[u'10.181.184.0/24', u'172.16.0.0/30', u'172.16.0.12/30', u'172.16.0.8/30', u'172.16.2.0/30', u'3.3.3.3/32'], sid=''), Node(name=u'101058054', id=u'101058054', loopback='', portlist=[u'172.16.0.18', u'172.16.0.22', u'172.16.0.26', u'172.16.0.41', u'172.16.3.5'], pcc='', pcep_type='', prefix=[u'10.181.184.0/24', u'172.16.0.16/30', u'172.16.0.20/30', u'172.16.0.24/30', u'172.16.0.40/30', u'172.16.3.4/30', u'6.6.6.6/32'], sid='')]
1615 2023-05-18 20:35:04.039 UTC root:pseudo_net_build INFO: []
1615 2023-05-18 20:35:04.054 UTC root:_get_url     INFO: status code: 200
1615 2023-05-18 20:35:04.057 UTC root:build_odl_topology ERROR: <type 'exceptions.KeyError'>
1615 2023-05-18 20:35:04.058 UTC root:getTopo      INFO: Failed to get topo: could not reach odl-server?
1615 2023-05-18 20:35:04.058 UTC root:post         INFO: {"response": [{"cause": "could not reach odl-server?", "option": "topo", "success": false}]}
1615 2023-05-18 20:35:04.060 UTC root:initialize   INFO: Init 2 done - debug saved
1615 2023-05-18 20:35:04.060 UTC root:rest_interface_parser INFO: Commands Relieved: {u'option': u'list_all'}
1615 2023-05-18 20:35:04.068 UTC root:get_url      INFO: Url get Status: 200
1615 2023-05-18 20:35:04.068 UTC root:listAllLsp   INFO: list: [], formatted: []
1615 2023-05-18 20:35:04.069 UTC root:post         INFO: {"response": [{"list": [], "option": "list_all", "success": true}]}

Please help me. what happes ?
