### ISSUE TITLE
ODL topology data is invalid

### ISSUE THREAD

**Issue by ralphchen** [CiscoDevNet/pathman-sr#18]
hi all

when i prepared everything on ODL(bgp-ld/pcep) that i can get the topology from YANG UI on opendaylight, and i run the pathman on the same node .
then i opened http://localhost:8020/cisco-ctao/apps/pathman_sr/index.html
it tells me topology data is invalid.

here's the pathman log on the server:

> 32502 2019-09-16 22:31:14.505 UTC root:pseudo_net_build INFO: []
> 32502 2019-09-16 22:31:14.521 UTC root:_get_url     INFO: status code: 200
> 32502 2019-09-16 22:31:14.521 UTC root:build_odl_topology ERROR: <type 'exceptions.KeyError'>
> 32502 2019-09-16 22:31:14.522 UTC root:getTopo      INFO: Failed to get topo: could not reach odl-server?
> 32502 2019-09-16 22:31:14.522 UTC root:post         INFO: {"response": [{"cause": "could not reach odl-server?", "option": "topo", "success": 
> false}]}
> 32502 2019-09-16 22:31:14.524 UTC root:initialize   INFO: Init 2 done - debug saved
> 32502 2019-09-16 22:31:14.525 UTC root:rest_interface_parser INFO: Commands Relieved: {u'option': u'list_all'}
> 32502 2019-09-16 22:31:14.539 UTC root:get_url      INFO: Url get Status: 200
> 32502 2019-09-16 22:31:14.540 UTC root:listAllLsp   INFO: list: [], formatted: []
> 32502 2019-09-16 22:31:14.540 UTC root:post         INFO: {"response": [{"list": [], "option": "list_all", "success": true}]}

it seems caused by "root:getTopo      INFO: Failed to get topo: could not reach odl-server?"
i'm new to ODL and pathman, any suggestion and where to start troubleshooting on it?

thanks in advance

**Comment by ralphchen** [comment]
i found the cause

the default url of bgp-rib in pathman_ini.py is example-bgp-rib

>         url = '{}://{}:{}/restconf/operational/bgp-rib:bgp-rib/rib/bgp-example/loc-rib/tables/bgp-linkstate:linkstate-address-family/bgp-linkstate:linkstate-subsequent-address-family/linkstate-routes'

however i followed the ODL guide which is bgp-example . after i correct this, the topology is shown up.

**Comment by philkaren22** [comment]
Hello ,

I'm having trouble using Pathman SR with Junipers vMX routers.
I am facing the same error as you using ODL Beryllium.
can someone help me or do i need to change ODL version?
