### ISSUE TITLE
not able to deploy SRTE in pathman-sr

### ISSUE THREAD

**Issue by mamei-c** [CiscoDevNet/pathman-sr#19]
hi,

My topology is displaying as expected, but "Path Setup" is not working.
pls refer to below for more details.

++++++++++Version+++++++++++++
Cisco IOS XR Software, Version 7.2.1.32I
opendaylight-user@root>version
4.2.6

++++++++++Error Msg++++++++++++
50 2020-07-03 07:39:48.577 UTC root:__init__     ERROR: unexpected item: {u'local-node-descriptors': {u'domain-id': 0, u'as-number': 1, u'isis-node': {u'iso-system-id': u'AAAAAAAD'}}, u'remote-node-descripto
rs': {u'domain-id': 0, u'as-number': 1, u'isis-node': {u'iso-system-id': u'AAAAAAAJ'}}, u'path-id': 0, u'protocol-id': u'isis-level2', u'attributes': {u'origin': {u'value': u'igp'}, u'link-attributes': {u'me
tric': 10}, u'ipv4-next-hop': {u'global': u'9.9.9.9'}, u'local-pref': {u'pref': 100}}, u'identifier': 0, u'route-key': u'AAIARQIAAAAAAAAAAAEAABoCAAAEAAAAAQIBAAQAAAAAAgMABgAAAAAAAwEBABoCAAAEAAAAAQIBAAQAAAAAAg
MABgAAAAAACQ=='}
50 2020-07-03 07:39:48.958 UTC root:get_netconf  ERROR: No rid for: 54b42d836e9c4a24a402e7505cf98754
50 2020-07-03 07:39:48.958 UTC root:node_sr_update ERROR: No sid for: R9
50 2020-07-03 07:39:48.958 UTC root:node_sr_update ERROR: No sid for: R1
50 2020-07-03 07:39:48.959 UTC root:node_sr_update ERROR: No sid for: R2
50 2020-07-03 07:39:48.959 UTC root:node_sr_update ERROR: No sid for: R3

++++++++++PCC nodes cfg++++++++++++
  pcc
   source-address ipv4 9.9.9.1
   pce address ipv4 9.9.9.29

router isis 1
 is-type level-2-only
 net 49.0000.0000.0001.00
 distribute link-state level 2
 address-family ipv4 unicast
  metric-style wide
  mpls traffic-eng level-2-only
  mpls traffic-eng router-id Loopback9
  segment-routing mpls

**Comment by mamei-c** [comment]
resolved by changing sr configuration

**Comment by philkaren22** [comment]
what is the configuration of sr that you used ?
