### ISSUE TITLE
How to compose an SR path using Adjacency SID

### ISSUE THREAD

**Issue by sshrabah** [CiscoDevNet/pathman-sr#2]
Hi, 
I  want to modify the code to express an SR path using Node-SIDs and Adj-SIDs. However, in the POST Rest request, i can not find how to express the Adjacency-SID. 

Node-SIDs are expressed as follow

```
<subobject>
<loose>false</loose>
<sid-type xmlns="urn:opendaylight:params:xml:ns:yang:pcep:segment:routing">ipv4-node-id</sid-type>
<m-flag xmlns="urn:opendaylight:params:xml:ns:yang:pcep:segment:routing">true</m-flag>
<sid xmlns="urn:opendaylight:params:xml:ns:yang:pcep:segment:routing">16028</sid>
</subobject>
```

Is there a way to express an Adjacency SID ?

**Comment by zverevalexei** [comment]
Hi @sshrabah 

I reported the issue to our engineers. They will reach out to you and address it soon.

Thanks!

**Comment by sshrabah** [comment]
Hi @zverevalexei 
thank for the quick response, hope we hear for the engineers soon ;)

bests.

**Comment by nikmon2** [comment]
Hi,

Pathman_sr detects both formats for existing LSPs, so you can test to create with postman and see if the new LSPs are detected by pathman_sr.

Formats for ERO's below.
(I believe I tested both examples)

Cheers,
Niklas

Node id:
```json
 "ero": {
   "subobject": [{
   "loose": false,
   "sid-type": "ipv4-node-id",
   "sid": 16027,
   "m-flag": true,
   "ip-address": "198.19.1.27"
    }]
```

Adjacency:
```json
 "ero": {
   "subobject": [{
   "loose": false,
   "sid-type": "ipv4-adjacency",
   "sid": 16022,
   "m-flag": true,
   "remote-ip-address": "49.0.0.22",
   "local-ip-address": "49.0.0.30"
    }]
   }
```

**Comment by zverevalexei** [comment]
@sshrabah Given no reply has been received, I'm closing the issue assuming you've achieved what you needed. Thank you.
